# Spring
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/study/spring-data-jpa/db/data-jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

# logging
logging:
  level:
    org.hibernate.SQL: debug